spring: 
  dubbo: 
    application:
      name: provider
    server: true
    registry: 
      address: zookeeper://127.0.0.1:2181
#    protocol: 
#      name: dubbo  #默认值
#      port: 20880  #默认值
 