spring:
   datasource:
      url: jdbc:mysql://192.168.1.224:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      hikari:
         connection-timeout: 30000
         minimum-idle: 5
         maximum-pool-size: 50