spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.101.136.249:18765/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zzy123456
  jpa:
    show-sql: true 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl: 
          auto: update