server:
  port: 5002
  servlet:
    context-path: /redisLockService
spring:
  redis:
    # Redis数据库索引
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器端口
    port: 6379
    # Redis服务器连接密码
    #password:
    # 连接池配置
    lettuce:
      pool:
        # 连接池最大连接数 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1ms
        max-wait: -1ms
        # 连接池中最大空闲连接 默认 0
        max-idle: 0
        # 连接池中最小空闲连接 默认 0
        min-idle: 0
    # 连接超时时间
    timeout: 3000
logging:
  level:
    com.zzy.redis.lock.jedis.controller: trace

custom:
  redis:
    database: 0
    mode: cluster
    #password: ''
    pool:
      conn-timeout: 3000
      max-active: 8
      max-idle: 16
      max-wait: 3000
      min-idle: 8
      size: 10
      so-timeout: 3000
    single:
      address: localhost:6379
    sentinel:
          fail-max: 3
          master: business-master
          master-onlyWrite: true
          nodes: ''
    cluster:
          failed-attempts: 3
          master-connection-pool-size: 64
          nodes: 192.168.164.128:9001,192.168.164.128:9002,192.168.164.128:9003,192.168.164.128:9004,192.168.164.128:9005,192.168.164.128:9006
          read-mode: SLAVE
          retry-attempts: 3
          retry-interval: 1500
          scan-interval: 1000
          slave-connection-pool-size: 64
    timeout: 3000


