mysql:
   datasource1:
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
#      driver-class-name: com.mysql.jdbc.Driver
   datasource2:      
      jdbc-url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
 #     driver-class-name: com.mysql.jdbc.Driver