spring:
  datasource:
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  # 缓存配置
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml